export const problemSolvingChallenges = [
  {
    id: 1,
    title: "Equipment Downtime",
    description: "Injection line shuts down 4-5 times per shift",
    context:
      "The equipment is over 10 years old. No preventive maintenance schedule. Operators unsure how to troubleshoot. When it breaks, we lose 30-60 minutes per incident.",
    difficulty: "hard",
    baseXp: 150,
    areaName: "Injection Molding",
    possibleCauses: [
      {
        id: 1,
        category: "MACHINES",
        cause: "Old machinery (10+ years)",
        quality: "excellent",
      },
      {
        id: 2,
        category: "MACHINES",
        cause: "No preventive maintenance",
        quality: "good",
      },
      {
        id: 3,
        category: "METHODS",
        cause: "No standard procedures",
        quality: "good",
      },
      {
        id: 4,
        category: "PEOPLE",
        cause: "Operator skill gap",
        quality: "acceptable",
      },
      {
        id: 5,
        category: "MEASUREMENT",
        cause: "No real-time monitoring",
        quality: "acceptable",
      },
      {
        id: 6,
        category: "MATERIALS",
        cause: "Low-quality spare parts",
        quality: "poor",
      },
    ],
    correctRootCauseId: 1,
    correctCategories: ["MACHINES", "METHODS", "PEOPLE"],
    correctSolution:
      "Implement preventive maintenance program with weekly equipment checks, spare parts stock, and operator training",
  },
  {
    id: 2,
    title: "WIP Pile-up",
    description: "Assembly station 3 consistently builds WIP backlog",
    context:
      "Station 3 experiences unbalanced workload compared to upstream. Visual controls show items waiting >15 minutes.",
    difficulty: "medium",
    baseXp: 100,
    areaName: "Assembly Line",
    possibleCauses: [
      { id: 1, category: "METHODS", cause: "Unbalanced work content", quality: "good" },
      { id: 2, category: "PEOPLE", cause: "Cross-training gaps", quality: "acceptable" },
      { id: 3, category: "MEASUREMENT", cause: "No takt visualization", quality: "acceptable" },
      { id: 4, category: "MACHINES", cause: "Frequent micro-stops", quality: "good" },
    ],
    correctRootCauseId: 1,
    correctCategories: ["METHODS", "PEOPLE"],
    correctSolution: "Rebalance tasks and add visual takt tracking at station 3",
  },
  {
    id: 3,
    title: "Quality Defects",
    description: "Paint shop sees recurring surface blemishes",
    context: "Customers report visible blemishes in 3% of batches, often from dust contamination.",
    difficulty: "medium",
    baseXp: 100,
    areaName: "Paint Shop",
    possibleCauses: [
      { id: 1, category: "ENVIRONMENT", cause: "Dust in booth", quality: "good" },
      { id: 2, category: "METHODS", cause: "Improper cleaning", quality: "acceptable" },
      { id: 3, category: "MATERIALS", cause: "Paint viscosity variation", quality: "acceptable" },
      { id: 4, category: "PEOPLE", cause: "Inconsistent prep", quality: "good" },
    ],
    correctRootCauseId: 1,
    correctCategories: ["ENVIRONMENT", "METHODS"],
    correctSolution: "Improve booth filtration and standardize cleaning between runs",
  },
  {
    id: 4,
    title: "Material Flow",
    description: "Warehouse pickers detour frequently",
    context: "Pick paths zig-zag due to poor layout; missing signage for fast-movers.",
    difficulty: "easy",
    baseXp: 75,
    areaName: "Warehouse",
    possibleCauses: [
      { id: 1, category: "METHODS", cause: "No optimized pick path", quality: "good" },
      { id: 2, category: "ENVIRONMENT", cause: "Cluttered aisles", quality: "acceptable" },
      { id: 3, category: "MEASUREMENT", cause: "No travel time tracking", quality: "poor" },
    ],
    correctRootCauseId: 1,
    correctCategories: ["METHODS", "ENVIRONMENT"],
    correctSolution: "Re-layout warehouse with ABC zoning and clear signage",
  },
  {
    id: 5,
    title: "Inconsistent Takt Time",
    description: "Assembly takt fluctuates by ±25%",
    context: "Operators improvise sequence; no clear standard work or WIP caps.",
    difficulty: "hard",
    baseXp: 150,
    areaName: "Assembly Line",
    possibleCauses: [
      { id: 1, category: "METHODS", cause: "Lack of standard work", quality: "good" },
      { id: 2, category: "MEASUREMENT", cause: "No real-time takt display", quality: "acceptable" },
      { id: 3, category: "PEOPLE", cause: "Training inconsistencies", quality: "acceptable" },
      { id: 4, category: "MACHINES", cause: "Unreliable fixtures", quality: "good" },
    ],
    correctRootCauseId: 1,
    correctCategories: ["METHODS", "MEASUREMENT"],
    correctSolution: "Introduce standard work, daily coaching, and visible takt timer",
  },
  {
    id: 6,
    title: "Operator Errors",
    description: "Injection operators misload parts twice per shift",
    context: "Training materials outdated; similar-looking molds cause confusion.",
    difficulty: "medium",
    baseXp: 100,
    areaName: "Injection Molding",
    possibleCauses: [
      { id: 1, category: "PEOPLE", cause: "Insufficient training", quality: "good" },
      { id: 2, category: "METHODS", cause: "No visual aids", quality: "acceptable" },
      { id: 3, category: "MATERIALS", cause: "Look-alike components", quality: "acceptable" },
    ],
    correctRootCauseId: 1,
    correctCategories: ["PEOPLE", "METHODS"],
    correctSolution: "Refresh training and add poka-yoke visual aids",
  },
  {
    id: 7,
    title: "Safety Incidents",
    description: "Slip hazards in paint shop increase",
    context: "Spill response inconsistent; ventilation causes condensation near drains.",
    difficulty: "hard",
    baseXp: 150,
    areaName: "Paint Shop",
    possibleCauses: [
      { id: 1, category: "ENVIRONMENT", cause: "Condensation on floor", quality: "good" },
      { id: 2, category: "METHODS", cause: "No spill SOP", quality: "acceptable" },
      { id: 3, category: "MEASUREMENT", cause: "No near-miss tracking", quality: "poor" },
    ],
    correctRootCauseId: 1,
    correctCategories: ["ENVIRONMENT", "METHODS"],
    correctSolution: "Improve ventilation balance and implement clear spill SOP",
  },
  {
    id: 8,
    title: "Inventory Inaccuracy",
    description: "Warehouse counts off by 3-5% monthly",
    context: "Cycle counts irregular; receiving and picking share scanners without confirmations.",
    difficulty: "medium",
    baseXp: 100,
    areaName: "Warehouse",
    possibleCauses: [
      { id: 1, category: "MEASUREMENT", cause: "No cycle count cadence", quality: "acceptable" },
      { id: 2, category: "METHODS", cause: "No scan confirmation", quality: "good" },
      { id: 3, category: "PEOPLE", cause: "Training gaps for temp staff", quality: "acceptable" },
    ],
    correctRootCauseId: 2,
    correctCategories: ["MEASUREMENT", "METHODS"],
    correctSolution: "Introduce weekly cycle counts and mandatory scan confirmation",
  },
];
